import { BASE_URL } from "./route";

export const USER_ROUTES = {
    LOGOUT: `${BASE_URL.USER}/logout`,
    CHANGE_PASSWORD: `${BASE_URL.USER}/change-password`,
    GET_TURFS: `${BASE_URL.USER}/get-Turfs`,
    SLOTS: (turfId: string, date: string) =>`${BASE_URL.USER}/slots?turfId=${turfId}&date=${date}`,
    PAYMENT_CREATE_INTENT: `${BASE_URL.USER}/payments/create-payment-intent`,
    SHARED_SLOT_PAYMENT: `${BASE_URL.USER}/payments/create-payment-intent`,
    SLOT_UPDATE: `${BASE_URL.USER}/slots`,
    GET_ALL_BOOKING: `${BASE_URL.USER}/bookings`,
    SHARED_SLOT_JOIN: `${BASE_URL.USER}/joinSlot`,
    GET_SLOT_DATA: (slotId: string) =>`${BASE_URL.USER}/getSlot?slotId=${slotId}`,
    FETCH_HOSTED_GAMES: `${BASE_URL.USER}/hosted-games`,
    GET_JOINED_GAME_DETAILS: (bookingId: string | undefined) =>`${BASE_URL.USER}/joinedGameDetials?bookingId=${bookingId}`,
    CANCEL_BOOKING: `${BASE_URL.USER}/cancelJoinedGame`,
    CANCEL_BOOKING_SINGLE: `${BASE_URL.USER}/cancelSingleSlot`,
    GET_WALLET_DETAILS: `${BASE_URL.USER}/wallet`,
    GET_CHAT_ROOMS: (userId: string) =>`${BASE_URL.USER}/getChatRooms?userId=${userId}`,
    CREATE_CHAT_ROOM: `${BASE_URL.USER}/createChatRoom`,
    GET_WALLET_TRANSACTIONS: `${BASE_URL.USER}/wallet/transactions`,
    GET_WALLET_BALANCE: `${BASE_URL.USER}/wallet/balance`,
    GET_CHAT_ROOM_BY_GAME_ID: (gameId: string) =>`${BASE_URL.USER}/getChatRoomByGameId?gameId=${gameId}`,
    SAVE_FCM_TOKEN: `${BASE_URL.USER}/savefcm-token`,
    GET_NOTIFICATIONS: `${BASE_URL.USER}/notification`,
    UPDATE_NOTIFICATION: `${BASE_URL.USER}/notification`,
    GET_REVIEWS: (turfId: string) =>`${BASE_URL.USER}/getReview?turfId=${turfId}`,
    ADD_REVIEW: `${BASE_URL.USER}/review`,
    REFRESH_TOKEN: `${BASE_URL.USER}/refresh-token`,
};
